export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_QUIZES_BEGIN = 'GET_QUIZ_LIST_BEGIN';
export const GET_QUIZES_SUCCESS = 'GET_QUIZ_LIST_SUCCESS';
export const GET_QUIZES_FAILURE = 'GET_QUIZ_LIST_FAILURE';

export const CREATE_QUIZ_BEGIN = 'CREATE_QUIZ_BEGIN';
export const CREATE_QUIZ_SUCCESS = 'CREATE_QUIZ_SUCCESS';
export const CREATE_QUIZ_FAILURE = 'CREATE_QUIZ_FAILURE';
